name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger on tags that start with 'v'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          DOCKER_TAG=latest
        else
          DOCKER_TAG=${{ github.ref }}
        fi
        docker build -t sami/brudi-rclone:${DOCKER_TAG} .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push image to Docker Hub
      run: |
        docker push sami/brudi-rclone:${DOCKER_TAG}
